Repository meltdownjs/meltdown, pull requests merged in 2024-05, with the labels that each got.

#1 feat: add github action workflow for publishing packages to npm
  .github/workflows/publish.yml
Labels: enhancement

#4 feat: add release-please to ci
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .release-please-manifest.json
  release-please-config.json
Labels: feat

#5 feat: include biome completely
  .devcontainer/devcontainer.json
  .gitignore
  biome.json
  bun.lockb
  packages/biome-config/biome.json
  packages/biome-config/package.json
Labels: feat

#6 fix: use correct extra files path
  release-please-config.json
Labels: fix

#9 feat: @meltdownjs/biomejs-confg
  .release-please-manifest.json
  biome.json
  bun.lockb
  packages/biome-config/CHANGELOG.md
  packages/biomejs-config/biome.json
  packages/biomejs-config/package.json
  release-please-config.json
Labels: feat

#3 feat: @meltdownjs/cn
  .github/workflows/ci.yml
  bun.lockb
  packages/biomejs-config/biome.json
  packages/biomejs-config/package.json
  packages/cn/.gitignore
  packages/cn/README.md
  packages/cn/biome.json
  packages/cn/build.ts
  packages/cn/package.json
  packages/cn/src/index.test.ts
  packages/cn/src/index.ts
  packages/cn/tsconfig.json
Labels: feat

#11 chore: add cn to release-please config
  release-please-config.json
Labels: chore

#12 feat: use own import for types
  packages/cn/src/index.ts
Labels: feat

#14 feat: @meltdownjs/droppy
  .devcontainer/Dockerfile
  bun.lockb
  packages/droppy/.gitignore
  packages/droppy/README.md
  packages/droppy/biome.json
  packages/droppy/package.json
  packages/droppy/src/components/Option.tsx
  packages/droppy/src/constants.ts
  packages/droppy/src/hooks/useDropdownList.test.ts
  packages/droppy/src/hooks/useDropdownList.ts
  packages/droppy/src/hooks/useInfiniteComboBox.test.tsx
  packages/droppy/src/hooks/useInfiniteComboBox.ts
  packages/droppy/src/hooks/useInfiniteMultiComboBox.test.tsx
  packages/droppy/src/hooks/useInfiniteMultiComboBox.ts
  packages/droppy/src/hooks/useInfiniteMultiSelect.test.tsx
  packages/droppy/src/hooks/useInfiniteMultiSelect.ts
  packages/droppy/src/hooks/useInfiniteQueryResultVirtualizer.ts
  packages/droppy/src/hooks/useInfiniteSelect.test.tsx
  packages/droppy/src/hooks/useInfiniteSelect.ts
  packages/droppy/src/hooks/useMultiOptionSelectorCallback.ts
  packages/droppy/src/hooks/useMultiSelect.test.tsx
  packages/droppy/src/hooks/useMultiSelect.ts
  packages/droppy/src/hooks/useOptionSelectorCallback.ts
  packages/droppy/src/hooks/usePropsGetter.ts
  packages/droppy/src/hooks/useSelect.test.tsx
  packages/droppy/src/hooks/useSelect.ts
  packages/droppy/src/index.ts
  packages/droppy/src/test-types.d.ts
  packages/droppy/src/test-utils.tsx
  packages/droppy/src/types.d.ts
  packages/droppy/src/utils.ts
  packages/droppy/src/vite-env.d.ts
  packages/droppy/tsconfig.json
  packages/droppy/tsconfig.node.json
  packages/droppy/vite.config.ts
  packages/droppy/vitest.config.ts
  release-please-config.json
Labels: feat

#16 fix: remove typo in package.json
  packages/droppy/package.json
Labels: fix

#18 fix: remove typo in package.json
  packages/cn/package.json
Labels: fix

#21 feat: use `Vite` instead of `Bun.build`
  bun.lockb
  packages/cn/.gitignore
  packages/cn/build.ts
  packages/cn/package.json
  packages/cn/src/vite-env.d.ts
  packages/cn/tsconfig.json
  packages/cn/vite.config.ts
Labels: feat

#20 feat: provide helper functions
  packages/droppy/src/index.ts
  packages/droppy/src/utils.test.ts
Labels: feat

#23 fix: Add missing `files` field in package.json
  packages/cn/package.json
Labels: fix

#26 chore: use latest bun version in devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: chore

#25 fix: ignore `dist` and `node_modules` directory
  packages/biomejs-config/biome.json
Labels: fix
